fix: strengthen types, simplify logic
cloudposse/terraform-aws-ecs-container-definition pull request #154
Opened 2022-08-09 04:01 UTC by obataku

## what
* enable & use optional attributes where AWS API marks fields optional
* remove redundant lookups
* strengthen types for `log_configuration`, `repository_credentials`, `system_controls`, `container_definition`
* reorder object var attributes to match AWS docs
* simplify log configuration sanitization/munging
* simplify secret & environment var sorting
* expose unencoded container definition output directly without requiring pointless `jsonencode`/`jsondecode` cycle

## why
* [`optional`](https://www.terraform.io/language/expressions/type-constraints#experimental-optional-object-type-attributes) obviates `lookup(..., null)` calls for objects
* [`lookup(o, k)`](https://www.terraform.io/language/functions/lookup#lookup-function) without a `default` is deprecated in favor of `o[k]`
* `log_configuration`, `repository_credentials`, and `system_controls` had needlessly opaque `any` types which hinder DX and make subtle bugs more likely (e.g. in the types of `log_configuration.options` values)
* since all attributes of `container_definition` are now typed there's no reason not to type it as well
* following the AWS documentation's field order makes types easier to verify for completeness & correctness
* typing `log_configuration` appropriately obviates explicit `tostring` & `null` handling
* env/secret map sorting can be dramatically simplified since `for`-expressions iterate over maps & objects by key in lexicographic order
* `jsonencode`-ing the final container definition only to `jsondecode` for `json_map_object` is redundant

2022-08-09 04:49 UTC, obataku commented on variables.tf
> +  default     = null
the field is not required so there's no reason to specify `[]` rather than `null`
https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-volumesFrom

2022-08-09 04:49 UTC, obataku commented on variables.tf
> +  default     = null
likewise https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-mountPoints

2022-08-09 04:49 UTC, obataku commented on variables.tf
> +    options = optional(map(string))
explicitly optional per AWS docs
https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_FirelensConfiguration.html#ECS-Type-FirelensConfiguration-options

2022-08-09 04:49 UTC, obataku commented on examples/complete/variables.tf
> +    capabilities = optional(object({
`optional`s per AWS
https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_LinuxParameters.html

2022-08-18 15:48 UTC, obataku commented
/test all

2022-12-05 03:42 UTC, nitrocode requested changes
Please see discussion in https://github.com/cloudposse/terraform-aws-ecs-web-app/pull/189

2023-04-24 14:12 UTC, Gowiem commented
@obataku can you get back to Nitro's requested changes and deal with the branch conflicts that you have? And if no longer relevant, feel free to close out. Thanks!

2023-06-07 11:39 UTC, goruha commented
/terratest

2023-06-07 11:47 UTC, merged