feat: :sparkles: added restart policies
cloudposse/terraform-aws-ecs-container-definition pull request #192
Opened 2024-09-09 05:30 UTC by JaydenMaalouf

## what

Adds container restart policies to the container definition

## why

This feature was introduced by AWS recently but has not made its way to this container

## references

closes #191

2024-09-09 16:26 UTC, Gowiem requested changes
Unfortunately, we need to run some automation to pass our tests. Mind doing the following locally, adding + committing the result, and pushing to your branch?

```
make init
make readme
```

Thanks!

2024-09-09 16:26 UTC, Gowiem commented on variables.tf
> +    enabled              = optional(bool)
Will this variable be valid if something is supplied, but `enabled` is left out? Maybe this should be the one required argument to this var?

2024-09-10 23:38 UTC, JaydenMaalouf commented on variables.tf
> +    enabled              = optional(bool)
Yeah, I'm not sure - I just went off what the AWS Console generated haha
I can make this one non-optional if that is preferred?

2024-09-12 07:00 UTC, JaydenMaalouf commented
> ```
> make init
> make readme
> ```

Seems `init` and `readme` are not valid Makefile targets in the root
`init` appears to be valid int he test folder but no `readme` still
Is there something I'm missing?

2024-09-17 03:16 UTC, JaydenMaalouf commented
> I wonder if you have a bad version of `make`?

Turns out the issue was running it on a Windows shell. Switched to WSL and reran make. Seemed to work!

2024-09-17 20:01 UTC, goruha commented
@JaydenMaalouf  could you pls add a description to this input
https://github.com/cloudposse/terraform-aws-ecs-container-definition/blob/main/examples/complete/variables.tf#L1

I know that's not a part of the PR changes, but unfortunately, we test all terraform files and have such side effects.
cc @Gowiem

2024-10-08 03:02 UTC, the-lay commented
Is there anything that can be done to expedite this PR? It seems like it's already complete, but happy to contribute.

2024-10-08 16:56 UTC, Gowiem commented
/terratest

2024-12-21 19:28 UTC, tovbinm commented
Folks, can we please have this merged?

2024-12-21 20:10 UTC, osterman commented
@tovbinm not until tests are passing

2025-01-22 22:33 UTC, Gowiem commented
@JaydenMaalouf friendly ping on this. Can you circle back around and get tests passing so we can get this merged?

2025-02-28 19:19 UTC, closed without merging

2025-02-28 20:08 UTC, tovbinm commented
"amazing"!